version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    env_file: .env
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./init_postgres.sh:/docker-entrypoint-initdb.d/init_postgres.sh
  core:
    image: ghcr.io/eclipse-pass/pass-core-main:0.2.0-SNAPSHOT
    build:
      context: .
    env_file: .env
    ports:
      - '8080:8080'    
volumes:
  db:
    driver: local
