# This workflow will update the pass-support Docker images in GHCR and update the pass-support config
#   in pass-docker

name: Update Docker image

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Update pass-support Docker images in GHCR
      - name: Check out latest pass-support
        uses: actions/checkout@v3

      - name: "Set up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build new package"
        run: mvn -U -B -V -ntp clean verify

      - name: "Get image tag"
        id: image_tag
        run: echo "IMAGE_TAG=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`" >> $GITHUB_OUTPUT

      - name: "Upload Docker images to GHCR"
        run: |
          docker push ghcr.io/eclipse-pass/deposit-services-core:${{ steps.image_tag.outputs.IMAGE_TAG }}
          docker push ghcr.io/eclipse-pass/pass-notification-service:${{ steps.image_tag.outputs.IMAGE_TAG }}
