name: pass-core Continuous Integration
on: [ pull_request, workflow_dispatch ]

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  print-workflow-description:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a CI build of branch ${{ github.ref }} in repository ${{ github.repository }}"
      - run: echo "This job was triggered by a ${{ github.event_name }} event and is running on a ${{ runner.os }} server"

  run-tests:
    name: "Run Unit & Integration Tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v2
      - name: "Set up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: "Cache Maven packages"
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m3-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m3
      - name: "Run unit & integration tests"
        run: mvn -U -B -V -ntp verify --file pom.xml
