name: Publish SNAPSHOT to Sonatype
# TODO: Not quite complete. Need to make sure current version is a SNAPSHOT version
# before proceeding with the publishing - because there will be some commits on `main`
# that will be associated with full releases
on:
  # push:
  #   branches:
  #     - 'main'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java & Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          server-id: ossrh
          # User/pass refer to ENV VARs set below
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Publish SNAPSHOT
        run: |
          cat ~/.m2/settings.xml
          mvn -B --no-transfer-progress clean deploy
        env:
          # Add OSSRH_USERNAME and OSSRH_PASSWORD as GH secrets
          # https://docs.github.com/en/actions/security-guides/encrypted-secrets
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
