name: Publish SNAPSHOT to Sonatype

on:
  # push:
  #   branches:
  #     - 'main'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java & Maven
        uses: actions/setup-java@v3
        with:
          java-version: 11
          server-id: ossrh
          # User/pass refer to ENV VARs set below
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Publish SNAPSHOT
        run: mvn deploy
        env:
          # Add OSSRH_USERNAME and OSSRH_TOKEN as GH secrets
          # https://docs.github.com/en/actions/security-guides/encrypted-secrets
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
